Repository IgniteUI/igniteui-cli, pull requests merged in 2018-12, with the labels that each got.

#419 cli-config schematic refactoring
  lib/project-utility/TypeScriptFileUpdate.ts
  lib/project-utility/TypeScriptUtils.ts
  package-lock.json
  package.json
  schematics/cli-config/index.spec.ts
  schematics/cli-config/index.ts
  schematics/tslint.json
  spec/unit/ts-transform/TypeScriptFileUpdate-spec.ts
  spec/unit/ts-transform/TypeScriptUtils-spec.ts
  tslint.json
Labels: angular, status: verified

#405 New add command --skip-route argument #368
  lib/commands/add.ts
  lib/templates/AngularTemplate.ts
  lib/templates/IgniteUIForAngularTemplate.ts
  lib/templates/ReactTemplate.ts
  lib/templates/jQueryTemplate.ts
  lib/types/Template.d.ts
  lib/types/TemplateArgs.d.ts
  spec/unit/add-spec.ts
  spec/unit/base-templates/AngularTemplate-spec.ts
  spec/unit/base-templates/IgniteUIForAngularTemplate-spec.ts
Labels: commands, status: verified

#418 Add view or component in a folder.
  lib/Util.ts
  lib/commands/add.ts
  lib/templates/AngularTemplate.ts
  lib/templates/IgniteUIForAngularTemplate.ts
  lib/templates/ReactTemplate.ts
  lib/templates/jQueryTemplate.ts
  spec/acceptance/add-spec.ts
  spec/unit/add-spec.ts
Labels: angular, enhancement, status: verified

#426 fix(igx-ts): Batch editing template relative dep path
  lib/templates/IgniteUIForAngularTemplate.ts
  templates/angular/igx-ts/grid/grid-batch-editing/files/src/app/__path__/__name__.component.html
  templates/angular/igx-ts/grid/grid-batch-editing/files/src/app/__path__/grid-transaction.component.ts
  templates/angular/igx-ts/grid/grid-batch-editing/index.ts
Labels: status: verified

#423 Step by step mode: Skip framework/project type selectiion with config
  lib/PromptSession.ts
  lib/config/defaults.json
  lib/types/Config.d.ts
  package-lock.json
  package.json
  spec/acceptance/add-spec.ts
  spec/acceptance/config-spec.ts
  spec/acceptance/new-spec.ts
  spec/unit/PromptSession-spec.ts
Labels: feature, status: verified, step by step

#425 Fix CustomDateSummary result
  templates/angular/igx-ts/grid/grid-summaries/files/src/app/__path__/__name__.component.ts
Labels: status: verified

#427 Update Ignite UI for Angular templates to latest 7.1.0 release and ng cli latest
  templates/angular/igx-ts/projects/_base/files/package.json
  templates/angular/igx-ts/projects/_base/files/src/polyfills.ts
  templates/angular/igx-ts/projects/_base/files/tslint.json
  templates/angular/igx-ts/projects/side-nav-auth/files/package.json
Labels: angular

#428 Attempt to migrate summaries operand change
  migrations/migration-collection.json
  migrations/update-3_2/index.spec.ts
  migrations/update-3_2/index.ts
Labels: angular, migration

#429 chore: Update default project ignteui-angular package to 6.x.х
  templates/angular/igx-ts/projects/empty/files/package.json
Labels: status: verified
