Repository IgniteUI/igniteui-cli, pull requests merged in 2018-05, with the labels that each got.

#276 Update igniteui-cli proj versions
  lib/templates/jQueryTemplate.ts
  templates/angular/ig-ts/projects/empty/files/package.json
  templates/jquery/js/grid/grid-export/files/index.html
  templates/jquery/js/grid/grid-export/index.ts
  templates/jquery/js/hierarchical-grid/hierarchical-grid-export/files/index.html
  templates/jquery/js/hierarchical-grid/hierarchical-grid-export/index.ts
  templates/jquery/js/projects/empty/files/package.json
  templates/jquery/js/tree-grid/tree-grid-export/files/index.html
  templates/jquery/js/tree-grid/tree-grid-export/index.ts
  templates/quickstart/angular/package.json
  templates/quickstart/jquery/index.html
  templates/quickstart/react/package.json
  templates/react/es6/projects/empty/files/package.json
Labels: status: in-test

#281 Update igx-ts proj to ng6
  templates/angular/igx-ts/custom-templates/monster-grid/files/src/app/__path__/__name__.component.scss
  templates/angular/igx-ts/projects/empty/files/.angular-cli.json
  templates/angular/igx-ts/projects/empty/files/README.md
  templates/angular/igx-ts/projects/empty/files/angular.json
  templates/angular/igx-ts/projects/empty/files/e2e/protractor.conf.js
  templates/angular/igx-ts/projects/empty/files/e2e/src/app.e2e-spec.ts
  templates/angular/igx-ts/projects/empty/files/e2e/src/app.po.ts
  templates/angular/igx-ts/projects/empty/files/e2e/tsconfig.e2e.json
  templates/angular/igx-ts/projects/empty/files/package.json
  templates/angular/igx-ts/projects/empty/files/src/app/app.component.ts
  templates/angular/igx-ts/projects/empty/files/src/browserslist
  templates/angular/igx-ts/projects/empty/files/src/environments/environment.ts
  templates/angular/igx-ts/projects/empty/files/src/karma.conf.js
  templates/angular/igx-ts/projects/empty/files/src/polyfills.ts
  templates/angular/igx-ts/projects/empty/files/src/tsconfig.app.json
  templates/angular/igx-ts/projects/empty/files/src/tsconfig.spec.json
  templates/angular/igx-ts/projects/empty/files/src/tslint.json
  templates/angular/igx-ts/projects/empty/files/src/typings.d.ts
  templates/angular/igx-ts/projects/empty/files/tsconfig.json
  templates/angular/igx-ts/projects/empty/files/tslint.json
Labels: status: verified

#283 fix: Add custom parameters to Google Analytics
  lib/PromptSession.ts
  lib/Util.ts
  lib/cli.ts
  lib/commands/add.ts
  lib/commands/build.ts
  lib/commands/config.ts
  lib/commands/doc.ts
  lib/commands/generate.ts
  lib/commands/list.ts
  lib/commands/new.ts
  lib/commands/quickstart.ts
  lib/commands/start.ts
  lib/commands/test.ts
  lib/types/GoogleAnalyticsParameters.d.ts
  package-lock.json
  scripts/install.ts
  scripts/uninstall.ts
  spec/acceptance/add-spec.ts
  spec/acceptance/config-spec.ts
  spec/acceptance/generate-spec.ts
  spec/acceptance/new-spec.ts
  spec/unit/cli-spec.ts
  spec/unit/generate-spec.ts
  spec/unit/test-spec.ts
Labels: bug, status: verified

#286 feat: Update project to use ng6
  templates/angular/ig-ts/projects/empty/files/package.json
Labels: status: in-test
