Repository IgniteUI/igniteui-cli, pull requests merged in 2018-02, with the labels that each got.

#167 test: Failing test for issue #148 fix
  lib/Util.ts
  lib/templates/AngularTemplate.ts
  lib/templates/ReactTemplate.ts
  spec/unit/Util-spec.ts
  spec/unit/add-spec.ts
  templates/angular/ig-ts/custom-templates/editors-calculation-form/index.ts
  templates/angular/ig-ts/grid/basic/index.ts
  templates/angular/ig-ts/grid/grid-custom/index.ts
  templates/angular/ig-ts/grid/grid-editing/index.ts
  templates/angular/ig-ts/grid/grid-export/index.ts
  templates/angular/ig-ts/grid/grid-templating/index.ts
  templates/angular/ig-ts/hierarchical-grid/hierarchical-grid-custom/index.ts
  templates/angular/ig-ts/hierarchical-grid/hierarchical-grid-editing/index.ts
  templates/angular/ig-ts/hierarchical-grid/hierarchical-grid-export/index.ts
  templates/angular/ig-ts/hierarchical-grid/hierarchical-grid/index.ts
  templates/angular/ig-ts/tree-grid/tree-grid-custom/index.ts
  templates/angular/ig-ts/tree-grid/tree-grid-editing/index.ts
  templates/angular/ig-ts/tree-grid/tree-grid-export/index.ts
  templates/angular/ig-ts/tree-grid/tree-grid-file-explorer/index.ts
  templates/angular/ig-ts/tree-grid/tree-grid/index.ts
  templates/react/es6/grid/basic/index.ts
  templates/react/es6/grid/grid-custom/index.ts
  templates/react/es6/grid/grid-editing/index.ts
  templates/react/es6/grid/grid-export/index.ts
  templates/react/es6/grid/grid-templating/index.ts
  templates/react/es6/hierarchical-grid/hierarchical-grid-custom/index.ts
  templates/react/es6/hierarchical-grid/hierarchical-grid-editing/index.ts
  templates/react/es6/hierarchical-grid/hierarchical-grid-export/index.ts
  templates/react/es6/hierarchical-grid/hierarchical-grid/index.ts
  templates/react/es6/tree-grid/tree-grid-custom/index.ts
  templates/react/es6/tree-grid/tree-grid-editing/index.ts
  templates/react/es6/tree-grid/tree-grid-export/index.ts
  templates/react/es6/tree-grid/tree-grid/index.ts
Labels: angular, bug, tests

#170 Mvenkov/remove selectors from templates
  templates/angular/ig-ts/bar-chart/default/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/column-chart/default/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/combo/combo/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/custom-templates/editors-calculation-form/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/doughnut-chart/default/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/editors/default/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/financial-chart/default/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/funnel-chart/default/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/grid/basic/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/grid/grid-custom/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/grid/grid-editing/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/grid/grid-export/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/grid/grid-templating/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/hierarchical-grid/hierarchical-grid-custom/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/hierarchical-grid/hierarchical-grid-editing/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/hierarchical-grid/hierarchical-grid-export/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/hierarchical-grid/hierarchical-grid/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/line-chart/default/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/pie-chart/default/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/projects/empty/files/src/app/components/home.component.ts
  templates/angular/ig-ts/radial-chart/default/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/tree-grid/tree-grid-custom/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/tree-grid/tree-grid-editing/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/tree-grid/tree-grid-export/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/tree-grid/tree-grid-file-explorer/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/tree-grid/tree-grid/files/src/app/components/__path__/__name__.component.ts
  templates/angular/igx-ts/carousel/default/files/src/app/__path__/__name__.component.ts
  templates/angular/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__name__.component.ts
  templates/angular/igx-ts/date-picker/default/files/src/app/__path__/__name__.component.ts
  templates/angular/igx-ts/grid/default/files/src/app/__path__/__name__.component.ts
  templates/angular/igx-ts/list/default/files/src/app/__path__/__name__.component.ts
  templates/angular/igx-ts/projects/empty/files/src/app/home/home.component.ts
  templates/angular/igx-ts/tabbar/default/files/src/app/__path__/__name__.component.ts
Labels: angular, angular-wrappers, bug

#178 chore: exclude templates from coverage report
  package.json
Labels: tests

#171 Automatically commit new project
  lib/Util.ts
  lib/commands/new.ts
  spec/acceptance/new-spec.ts
  spec/unit/new-spec.ts
Labels: feature

#174 Mvenkov/add generate command
  .vscode/launch.json
  lib/BaseProjectLibrary.ts
  lib/ProjectConfig.ts
  lib/TemplateManager.ts
  lib/Util.ts
  lib/cli.ts
  lib/commands/config.ts
  lib/commands/generate.ts
  lib/types/ProjectLibrary.d.ts
  spec/acceptance/add-spec.ts
  spec/acceptance/help-spec.ts
  spec/unit/TemplateManager-spec.ts
  spec/unit/generate-spec.ts
  templates/angular/ig-ts/generate/files/src/app/components/__path__/__name__.component.ts
  templates/angular/ig-ts/generate/template.json
  templates/angular/igx-ts/generate/files/src/app/__path__/__name__.component.css
  templates/angular/igx-ts/generate/files/src/app/__path__/__name__.component.html
  templates/angular/igx-ts/generate/files/src/app/__path__/__name__.component.spec.ts
  templates/angular/igx-ts/generate/files/src/app/__path__/__name__.component.ts
  templates/angular/igx-ts/generate/template.json
  templates/jquery/js/generate/files/index.html
  templates/jquery/js/generate/template.json
  templates/jquery/js/index.ts
  templates/react/es6/generate/files/client/components/__path__/index.js
  templates/react/es6/generate/files/client/pages/__path__/index.js
  templates/react/es6/generate/template.json
Labels: feature

#187 Mvenkov/generate command tests
  lib/commands/generate.ts
  lib/templates/jQueryTemplate.ts
  spec/acceptance/generate-spec.ts
  spec/unit/generate-spec.ts
  templates/angular/ig-ts/generate/template.json
  templates/angular/igx-ts/generate/template.json
  templates/jquery/js/generate/template.json
  templates/react/es6/generate/template.json
Labels: tests

#179 Unit tests for BaseProjectLibrary
  lib/BaseProjectLibrary.ts
  lib/PromptSession.ts
  lib/types/ProjectLibrary.d.ts
  spec/unit/BaseProjectLibrary-spec.ts
Labels: tests

#201 Step by step question / info messages updates
  lib/PromptSession.ts
  lib/Util.ts
  lib/cli.ts
  lib/commands/add.ts
  lib/commands/new.ts
  spec/unit/new-spec.ts
Labels: commands, step by step

#202 Update CLI version for igx-ts project
  templates/angular/igx-ts/projects/empty/files/package.json
Labels: angular
