Repository IgniteUI/igniteui-cli, pull requests merged in 2018-03, with the labels that each got.

#207 fix: change the regex to allow single letter name
  .vscode/launch.json
  lib/Util.ts
  lib/cli.ts
  lib/commands/add.ts
  lib/commands/build.ts
  lib/commands/config.ts
  lib/commands/generate.ts
  lib/commands/new.ts
  lib/commands/quickstart.ts
  lib/commands/start.ts
  lib/commands/test.ts
  spec/acceptance/help-spec.ts
  spec/acceptance/new-spec.ts
  spec/unit/add-spec.ts
Labels: bug

#203 feat: list command is working now
  .gitignore
  .vscode/launch.json
  lib/cli.ts
  lib/commands/generate.ts
  lib/commands/list.ts
  spec/acceptance/help-spec.ts
  spec/unit/list-spec.ts
  templates/angular/ig-ts/custom-templates/editors-calculation-form/index.ts
  templates/angular/igx-ts/custom-templates/awesome-grid/index.ts
  templates/angular/igx-ts/grid/default/index.ts
  templates/angular/igx-ts/grid/index.ts
  templates/angular/igx-ts/list/default/index.ts
  templates/angular/igx-ts/list/index.ts
  templates/jquery/js/custom-templates/dashboard-knockout/index.ts
  templates/jquery/js/custom-templates/editors-calculation-form/index.ts
  templates/jquery/js/custom-templates/er-dashboard/index.ts
  templates/jquery/js/grid/grid-custom/index.ts
  templates/jquery/js/grid/grid-editing/index.ts
  templates/jquery/js/grid/grid-export/index.ts
  templates/jquery/js/grid/grid-templating/index.ts
  templates/jquery/js/grid/grid/index.ts
  templates/jquery/js/hierarchical-grid/hierarchical-grid-custom/index.ts
  templates/jquery/js/hierarchical-grid/hierarchical-grid-editing/index.ts
  templates/jquery/js/hierarchical-grid/hierarchical-grid-export/index.ts
  templates/jquery/js/hierarchical-grid/hierarchical-grid/index.ts
  templates/jquery/js/tree-grid/file-explorer/index.ts
  templates/jquery/js/tree-grid/tree-grid-custom/index.ts
  templates/jquery/js/tree-grid/tree-grid-editing/index.ts
  templates/jquery/js/tree-grid/tree-grid-export/index.ts
  templates/jquery/js/tree-grid/tree-grid/index.ts
Labels: feature

#219 feat: add validation for configuration options in config set command
  lib/ProjectConfig.ts
  lib/commands/config.ts
  package-lock.json
  package.json
  spec/unit/config-spec.ts
Labels: feature

#231 test: finish coverage for new igx dependency changes, angular add acc…
  lib/project-utility/TypeScriptFileUpdate.ts
  lib/templates/IgniteUIForAngularTemplate.ts
  spec/acceptance/add-spec.ts
  spec/unit/base-templates/IgniteUIForAngularTemplate-spec.ts
  templates/angular/igx-ts/grid/default/index.ts
Labels: angular, angular-wrappers, tests

#236 docs: update readme with more links, step by step visual
  README.md
  assets/igniteui-cli.gif
Labels: documentation
