Repository IgniteUI/igniteui-cli, pull requests merged in 2020-06, with the labels that each got.

#752 fix(package-manager): manually update pckgJSON when adding packages
  packages/core/packages/PackageManager.ts
  packages/core/util/Util.ts
  spec/unit/packageManager-spec.ts
Labels: 5.1.x, commands, status: verified

#753 chore: put official version of igniteui-angular
  packages/igx-templates/igx-ts/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
Labels: version: 5.1.x

#755 fix(igx,upgrade): ignore projects without sourceRoot
  packages/igx-templates/Update.spec.ts
  packages/igx-templates/Update.ts
Labels: angular, commands, schematics, status: verified, version: 5.1.x

#743 refactor(upgrade): handle multiple licensed packages, #741
  packages/igx-templates/IgniteUIForAngularTemplate.ts
  packages/igx-templates/Update.spec.ts
  packages/igx-templates/Update.ts
  packages/igx-templates/package-resolve.spec.ts
  packages/igx-templates/package-resolve.ts
  packages/ng-schematics/src/cli-config/index.ts
  packages/ng-schematics/src/utils/theme-import.ts
Labels: angular, commands, status: verified, version: 5.1.x

#750 chore(upgrade): Logging a message that licensed package is already in…
  packages/igx-templates/Update.spec.ts
  packages/igx-templates/Update.ts
Labels: angular, commands, schematics, status: verified, version: 5.1.x

#735 update Ignite UI for jQuery to 20.1
  README.md
  packages/cli/templates/angular/ig-ts/projects/empty/files/package.json
  packages/cli/templates/jquery/js/generate/template.json
  packages/cli/templates/jquery/js/projects/empty/files/package.json
  packages/cli/templates/quickstart/angular/package.json
  packages/cli/templates/quickstart/jquery/index.html
  packages/cli/templates/quickstart/jquery/package.json
  packages/cli/templates/quickstart/react/package.json
  packages/cli/templates/react/es6/index.ts
  packages/cli/templates/react/es6/projects/empty/files/package.json
  spec/acceptance/generate-spec.ts
  spec/unit/packageManager-spec.ts
Labels: ignite-ui, jquery, status: verified, version: 5.1.x

#762 Updating the version of the DV related packages
  packages/igx-templates/igx-ts/bullet-graph/default/index.ts
  packages/igx-templates/igx-ts/category-chart/default/index.ts
  packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
  packages/igx-templates/igx-ts/financial-chart/default/index.ts
  packages/igx-templates/igx-ts/linear-gauge/default/index.ts
  packages/igx-templates/igx-ts/radial-gauge/default/index.ts
Labels: angular, ignite-ui, status: verified, version: 5.1.x

#761 Updating React LiveGrid to DataGrid
  packages/cli/templates/react/igr-es6/bullet-graph/default/files/src/views/__path__/index.js
  packages/cli/templates/react/igr-es6/bullet-graph/default/index.ts
  packages/cli/templates/react/igr-es6/category-chart/default/files/src/views/__path__/index.js
  packages/cli/templates/react/igr-es6/category-chart/default/index.ts
  packages/cli/templates/react/igr-es6/doughnut-chart/default/files/src/views/__path__/index.js
  packages/cli/templates/react/igr-es6/doughnut-chart/default/index.ts
  packages/cli/templates/react/igr-es6/financial-chart/default/files/src/views/__path__/index.js
  packages/cli/templates/react/igr-es6/financial-chart/default/index.ts
  packages/cli/templates/react/igr-es6/grid/basic/files/src/views/__path__/index.js
  packages/cli/templates/react/igr-es6/grid/basic/index.ts
  packages/cli/templates/react/igr-es6/grid/index.ts
  packages/cli/templates/react/igr-es6/linear-gauge/default/files/src/views/__path__/index.js
  packages/cli/templates/react/igr-es6/linear-gauge/default/index.ts
  packages/cli/templates/react/igr-es6/pie-chart/default/files/src/views/__path__/index.js
  packages/cli/templates/react/igr-es6/pie-chart/default/index.ts
  packages/cli/templates/react/igr-es6/projects/_base/files/package.json
  packages/cli/templates/react/igr-es6/radial-gauge/default/files/src/views/__path__/index.js
  packages/cli/templates/react/igr-es6/radial-gauge/default/index.ts
Labels: react, status: verified, version: 5.1.x

#763 feat: Adding a Dock Manager template for Angular
  packages/igx-templates/IgniteUIForAngularTemplate.ts
  packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.html
  packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.spec.ts
  packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.ts
  packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.module.ts
  packages/igx-templates/igx-ts/dock-manager/default/index.ts
  packages/igx-templates/igx-ts/dock-manager/index.ts
Labels: angular, status: verified, templates, version: 5.1.x

#765 chore(step-by-step): add test flag to show option to add all templates
  .vscode/launch.json
  packages/cli/lib/cli.ts
  packages/core/prompt/BasePromptSession.ts
  packages/core/util/App.ts
Labels: status: verified, step by step

#766 Change igx nav proj padding and adjust dock manager/fintech views
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.html
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/custom-templates/fintech-tree-grid/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/projects/_base/files/src/styles.scss
  packages/igx-templates/igx-ts/projects/side-nav/files/src/app/app.component.html
  packages/igx-templates/igx-ts/projects/side-nav/files/src/app/app.component.scss
  packages/igx-templates/igx-ts/projects/side-nav/files/src/app/app.component.ts
Labels: angular, status: verified, templates, version: 5.1.x

#760 test(package-resolve): add tests for `getUpgradeablePackages`
  packages/igx-templates/package-resolve.spec.ts
Labels: tests, version: 5.1.x

#770 feat: Adding a Map template for Angular
  packages/igx-templates/igx-ts/map/default/files/src/app/__path__/__filePrefix__.component.html
  packages/igx-templates/igx-ts/map/default/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/map/default/files/src/app/__path__/__filePrefix__.component.spec.ts
  packages/igx-templates/igx-ts/map/default/files/src/app/__path__/__filePrefix__.component.ts
  packages/igx-templates/igx-ts/map/default/index.ts
  packages/igx-templates/igx-ts/map/index.ts
Labels: angular, status: verified, templates, version: 5.1.x

#771 fix(igx,dock-manager): resolve package name from project
  packages/igx-templates/IgniteUIForAngularTemplate.ts
  packages/igx-templates/Update.spec.ts
  packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.spec.ts
  packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.component.ts
  packages/igx-templates/igx-ts/dock-manager/default/files/src/app/__path__/__filePrefix__.module.ts
  packages/igx-templates/igx-ts/dock-manager/default/index.ts
  packages/igx-templates/package-resolve.spec.ts
  packages/igx-templates/package-resolve.ts
  packages/ng-schematics/src/cli-config/index.ts
  packages/ng-schematics/src/utils/theme-import.ts
  spec/unit/base-templates/IgniteUIForAngularTemplate-spec.ts
Labels: angular, status: verified, templates, version: 5.2.x

#773 feat: remove angular as default choice for step by step #579
  packages/core/config/defaults.json
Labels: status: verified, step by step, version: 6.0.x

#772 fix: category reorder
  packages/core/templates/BaseProjectLibrary.ts
  packages/igx-templates/igx-ts/groups.json
  spec/unit/BaseProjectLibrary-spec.ts
Labels: status: verified, step by step, version: 5.2.x

#774 Add Angular 10 support
  packages/cli/migrations/update-2/index.spec.ts
  packages/cli/migrations/update-3/index.spec.ts
  packages/cli/migrations/update-3_2/index.spec.ts
  packages/cli/migrations/update-4_2_3/index.spec.ts
  packages/cli/migrations/update-5_0_0/index.spec.ts
  packages/cli/migrations/update-5_0_3/index.spec.ts
  packages/cli/package.json
  packages/cli/templates/angular/ig-ts/projects/empty/files/package.json
  packages/cli/templates/quickstart/angular/package.json
  packages/igx-templates/igx-ts/bullet-graph/default/index.ts
  packages/igx-templates/igx-ts/category-chart/default/index.ts
  packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
  packages/igx-templates/igx-ts/financial-chart/default/index.ts
  packages/igx-templates/igx-ts/linear-gauge/default/index.ts
  packages/igx-templates/igx-ts/map/default/index.ts
  packages/igx-templates/igx-ts/projects/_base/files/__dot__browserslistrc
  packages/igx-templates/igx-ts/projects/_base/files/__dot__editorconfig
  packages/igx-templates/igx-ts/projects/_base/files/angular.json
  packages/igx-templates/igx-ts/projects/_base/files/e2e/protractor.conf.js
  packages/igx-templates/igx-ts/projects/_base/files/e2e/src/app.po.ts
  packages/igx-templates/igx-ts/projects/_base/files/e2e/tsconfig.json
  packages/igx-templates/igx-ts/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/_base/files/src/polyfills.ts
  packages/igx-templates/igx-ts/projects/_base/files/tsconfig.app.json
  packages/igx-templates/igx-ts/projects/_base/files/tsconfig.base.json
  packages/igx-templates/igx-ts/projects/_base/files/tsconfig.json
  packages/igx-templates/igx-ts/projects/_base/files/tsconfig.spec.json
  packages/igx-templates/igx-ts/projects/_base/files/tslint.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/tsconfig.app.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/tsconfig.spec.json
  packages/igx-templates/igx-ts/radial-gauge/default/index.ts
Labels: angular, angular-wrappers, dependencies, enhancement, squash-merge, status: verified, version: 6.0.x

#775 test: Updating component groups test
  spec/unit/BaseProjectLibrary-spec.ts
Labels: angular, status: verified, tests
