Repository IgniteUI/igniteui-cli, pull requests merged in 2020-11, with the labels that each got.

#803 fix(dock-manager): Use correct module name in app.module import
  packages/igx-templates/igx-ts/dock-manager/default/index.ts
Labels: angular, dock-manager, status: verified, templates

#809 Dpetev/project fixes
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/app.component.html
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/external-auth.service.ts
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/local-storage.ts
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/user.service.ts
Labels: angular, version: 6.2.x

#808 chore(igx-ts, ig-ts): update to official 11 versions
  packages/cli/package.json
  packages/cli/templates/angular/ig-ts/projects/empty/files/package.json
  packages/cli/templates/quickstart/angular/package.json
  packages/igx-templates/igx-ts/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
  yarn.lock
Labels: angular, angular-wrappers, version: 7.0.x

#810 chore: update to igniteui-angular@11.0.0
  packages/igx-templates/igx-ts/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
Labels: angular, version: 7.0.x

#812 fix(*): ssr breaks because of localStorage ref
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/fake-backend.service.ts
Labels: angular, version: 6.2.x

#813 refactor(igx,custom-grid): udpate toolbar to new declarative setup
  packages/igx-templates/igx-ts/grid/grid-custom/files/src/app/__path__/__filePrefix__.component.html
  packages/igx-templates/igx-ts/grid/grid-custom/index.ts
Labels: angular, status: verified, version: 7.0.x

#814 fix(igx-ts): add local storage to spec
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/src/app/authentication/services/services.spec.ts
Labels: angular, version: 7.0.x

#815 fix(igx,custom-grid): assign allowFiltering when selected as option
  packages/igx-templates/igx-ts/grid/grid-custom/index.ts
Labels: angular, version: 7.0.x
