Repository IgniteUI/igniteui-cli, pull requests merged in 2020-10, with the labels that each got.

#796 chore(dv-components): Update to 10.1.3. #768
  packages/igx-templates/igx-ts/bullet-graph/default/index.ts
  packages/igx-templates/igx-ts/category-chart/default/index.ts
  packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
  packages/igx-templates/igx-ts/financial-chart/default/index.ts
  packages/igx-templates/igx-ts/linear-gauge/default/index.ts
  packages/igx-templates/igx-ts/radial-gauge/default/index.ts
Labels: angular, ignite-ui, status: verified

#795 Fix app generated with cli will not load because of an error
  packages/igx-templates/igx-ts/projects/_base/files/src/app/error-routing/error-routing.module.ts
Labels: angular, status: verified, version: 5.2.x

#798 fix(react-grid): Add missing module #791
  packages/cli/package.json
  packages/cli/templates/react/igr-es6/grid/basic/files/src/views/__path__/index.js
  packages/cli/templates/react/igr-es6/grid/basic/index.ts
Labels: grid, react, status: verified, version: 5.2.x

#799 chore: update to igniteui-angular beta
  packages/igx-templates/igx-ts/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
Labels: status: verified, version: 6.2.x

#801 fix(templates, crm grid, grid batch editing): Fixing issues in the tw…
  packages/igx-templates/igx-ts/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.html
  packages/igx-templates/igx-ts/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.ts
  packages/igx-templates/igx-ts/grid/grid-batch-editing/files/src/app/__path__/__filePrefix__.component.ts
Labels: grid, status: verified, templates
