Repository IgniteUI/igniteui-cli, pull requests merged in 2020-08, with the labels that each got.

#782 Update jszip to 350
  packages/igx-templates/igx-ts/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
Labels: dependencies, status: verified

#783 Updating igniteui-angular version to 10.1.0-beta.0
  packages/igx-templates/igx-ts/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
Labels: angular, status: verified

#784 Updating igniteui-angular version to "~10.1.0"
  packages/igx-templates/igx-ts/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
Labels: angular
