Repository IgniteUI/igniteui-cli, pull requests merged in 2021-01, with the labels that each got.

#822 Update treegrid & hierarchical grid custom template to declarative toolbar
  packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-custom/files/src/app/__path__/__filePrefix__.component.html
  packages/igx-templates/igx-ts/hierarchical-grid/hierarchical-grid-custom/index.ts
  packages/igx-templates/igx-ts/tree-grid/tree-grid-custom/files/src/app/__path__/__filePrefix__.component.html
  packages/igx-templates/igx-ts/tree-grid/tree-grid-custom/index.ts
Labels: angular, hierarchical-grid, status: verified, version: 7.0.x

#823 chore: update dv packages
  packages/igx-templates/igx-ts/bullet-graph/default/index.ts
  packages/igx-templates/igx-ts/category-chart/default/index.ts
  packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
  packages/igx-templates/igx-ts/financial-chart/default/index.ts
  packages/igx-templates/igx-ts/linear-gauge/default/index.ts
  packages/igx-templates/igx-ts/map/default/index.ts
  packages/igx-templates/igx-ts/radial-gauge/default/index.ts
Labels: status: verified, version: 7.0.x

#824 release: 7.0.2
  CHANGELOG.md
  packages/cli/package.json
  packages/core/package.json
  packages/igx-templates/package.json
  packages/ng-schematics/package.json
Labels: version: 7.0.x
