Repository IgniteUI/igniteui-cli, pull requests merged in 2021-12, with the labels that each got.

#962 Update lock file
  yarn.lock
Labels: version: 8.2.x

#961 feat: Update @use @forward and hsla
  packages/cli/migrations/update-4_2_3/index.spec.ts
  packages/cli/templates/webcomponents/igc-ts/projects/empty/files/index.html
  packages/igx-templates/Update.spec.ts
  packages/igx-templates/igx-ts/custom-templates/awesome-grid/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/themes/_mixins.scss
  packages/igx-templates/igx-ts/custom-templates/fintech-tree-grid/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/custom-templates/fintech-tree-grid/files/src/app/__path__/themes/_mixins.scss
  packages/igx-templates/igx-ts/projects/_base/files/src/styles.scss
  packages/igx-templates/igx-ts/projects/_base/index.ts
  packages/igx-templates/igx-ts/projects/empty/files/src/app/home/home.component.scss
  packages/igx-templates/igx-ts/tree/default/files/src/app/__path__/__filePrefix__.component.scss
  spec/unit/PromptSession-spec.ts
Labels: enhancement, :boom: status: in-test

#966 fix(schematics): fix home import without placeholder
  packages/igx-templates/igx-ts/projects/empty/files/src/app/home/home.component.scss
Labels: :white_check_mark: status: verified, version: 9.0.x

#965 Fixing some lint errors in grid views
  packages/cli/templates/webcomponents/igc-ts/grid/grid-editing/files/src/app/__path__/DataGridSharedData.ts
  packages/cli/templates/webcomponents/igc-ts/grid/grid-editing/files/src/app/__path__/__filePrefix__.ts
  packages/cli/templates/webcomponents/igc-ts/grid/grid-summaries/files/src/app/__path__/DataGridSharedData.ts
  packages/cli/templates/webcomponents/igc-ts/grid/grid-summaries/files/src/app/__path__/__filePrefix__.ts
  packages/cli/templates/webcomponents/igc-ts/projects/empty/files/src/app.ts
  packages/cli/templates/webcomponents/igc-ts/projects/empty/files/src/index.ts
Labels: :white_check_mark: status: verified, lint, web-components
