Repository IgniteUI/igniteui-cli, pull requests merged in 2023-06, with the labels that each got.

#1136 chore(igx): update DV 16
  packages/cli/lib/commands/upgrade.ts
  packages/cli/templates/webcomponents/igc-ts/grid/grid-editing/files/src/app/__path__/__filePrefix__.ts
  packages/core/packages/PackageManager.ts
  packages/igx-templates/igx-ts/bullet-graph/default/index.ts
  packages/igx-templates/igx-ts/category-chart/default/index.ts
  packages/igx-templates/igx-ts/custom-templates/awesome-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.ts
  packages/igx-templates/igx-ts/custom-templates/crm-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/files/src/app/__path__/__filePrefix__.component.ts
  packages/igx-templates/igx-ts/custom-templates/fintech-grid/index.ts
  packages/igx-templates/igx-ts/custom-templates/fintech-tree-grid/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/custom-templates/fintech-tree-grid/files/src/app/__path__/__filePrefix__.component.ts
  packages/igx-templates/igx-ts/custom-templates/fintech-tree-grid/index.ts
  packages/igx-templates/igx-ts/financial-chart/default/index.ts
  packages/igx-templates/igx-ts/linear-gauge/default/index.ts
  packages/igx-templates/igx-ts/map/default/index.ts
  packages/igx-templates/igx-ts/radial-gauge/default/index.ts
  spec/unit/packageManager-spec.ts
  spec/unit/upgrade-spec.ts
Labels: angular, :white_check_mark: status: verified, version: 12.0.x

#1090 chore(igx): enable back strict true
  packages/igx-templates/igx-ts/custom-templates/crm-grid/files/src/app/__path__/__filePrefix__.component.scss
  packages/igx-templates/igx-ts/projects/_base/files/tsconfig.json
Labels: angular, :white_check_mark: status: verified, version: 12.0.x

#1138 Removing eslint and ts-node from Angular proj
  packages/igx-templates/igx-ts/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
Labels: angular, :white_check_mark: status: verified

#1137 update wc to 4.3.0
  CHANGELOG.md
  packages/cli/package.json
  packages/cli/templates/webcomponents/igc-ts/projects/_base/files/package.json
  packages/cli/templates/webcomponents/igc-ts/projects/_base_with_home/files/package.json
  packages/core/package.json
  packages/igx-templates/package.json
  packages/ng-schematics/package.json
Labels: :white_check_mark: status: verified, web-components, version: 12.0.x
