Repository IgniteUI/igniteui-cli, pull requests merged in 2024-12, with the labels that each got.

#1353 Disable standalone lint check and fix paths for angular modules
  packages/cli/package.json
  packages/core/package.json
  packages/igx-templates/igx-ts-legacy/projects/_base/files/__dot__eslintrc.json
  packages/igx-templates/igx-ts-legacy/projects/_base/files/__dot__github/workflows/github-pages.yml
  packages/igx-templates/igx-ts-legacy/projects/_base_with_home/files/__dot__github/workflows/github-pages.yml
  packages/igx-templates/package.json
  packages/ng-schematics/package.json
Labels: angular-modules, :white_check_mark: status: verified

#1334 remove lite-server package and quickstart
  .eslintrc.json
  .gitignore
  .vscode/cSpell.json
  .vscode/launch.json
  .vscode/settings.json
  CHANGELOG.md
  README.md
  package.json
  packages/cli/README.md
  packages/cli/lib/cli.ts
  packages/cli/lib/commands/add.ts
  packages/cli/lib/commands/index.ts
  packages/cli/lib/commands/quickstart.ts
  packages/cli/lib/commands/types.ts
  packages/cli/package.json
  packages/cli/templates/quickstart/angular/.editorconfig
  packages/cli/templates/quickstart/angular/LICENSE
  packages/cli/templates/quickstart/angular/README.md
  packages/cli/templates/quickstart/angular/app/app.component.ts
  packages/cli/templates/quickstart/angular/app/app.module.ts
  packages/cli/templates/quickstart/angular/app/main.ts
  packages/cli/templates/quickstart/angular/favicon.ico
  packages/cli/templates/quickstart/angular/ignite-ui-cli.json
  packages/cli/templates/quickstart/angular/index.html
  packages/cli/templates/quickstart/angular/package.json
  packages/cli/templates/quickstart/angular/styles.css
  packages/cli/templates/quickstart/angular/systemjs.config.extras.js
  packages/cli/templates/quickstart/angular/systemjs.config.js
  packages/cli/templates/quickstart/angular/tsconfig.json
  packages/cli/templates/quickstart/angular/tslint.json
  packages/cli/templates/quickstart/jquery/index.html
  packages/cli/templates/quickstart/jquery/package.json
  packages/cli/templates/quickstart/react/index.html
  packages/cli/templates/quickstart/react/package.json
  packages/cli/templates/quickstart/react/src/App.js
  packages/cli/templates/quickstart/react/src/index.js
  packages/cli/templates/quickstart/react/webpack.config.js
  packages/core/templates/BaseTemplateManager.ts
  spec/acceptance/add-spec.ts
  spec/acceptance/help-spec.ts
  spec/unit/cli-spec.ts
  spec/unit/quickstart-spec.ts
  tsconfig-pack.json
  tsconfig.json
  yarn.lock
Labels: :white_check_mark: status: verified, squash-merge, dependencies

#1355 Add step in web components github pages workflow to fix navigation
  packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__github/workflows/github-pages.yml
Labels: :x: status: awaiting-test, web-components

#1356 chore: release version 14.3.4
  CHANGELOG.md
  packages/cli/package.json
  packages/core/package.json
  packages/igx-templates/package.json
  packages/ng-schematics/package.json
Labels: version: 14.3.x

#1357 chore: update official angular-eslint
  packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json
  packages/igx-templates/igx-ts-legacy/projects/side-nav-auth/files/package.json
  packages/igx-templates/igx-ts/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/side-nav-auth/files/package.json
Labels: angular-modules, angular-standalone, version: 14.3.x

#1358 fix web components router navigation
  packages/cli/package.json
  packages/cli/templates/webcomponents/igc-ts/projects/_base/files/__dot__github/workflows/github-pages.yml
  packages/core/package.json
  packages/igx-templates/package.json
  packages/ng-schematics/package.json
Labels: :white_check_mark: status: verified, web-components

#1360 chore: release version 14.3.5
  CHANGELOG.md
  packages/cli/package.json
  packages/core/package.json
  packages/igx-templates/package.json
  packages/ng-schematics/package.json
Labels: version: 14.3.x

#1361 fix(migrations): enable encapsulation for migrations
  packages/cli/migrations/migration-collection.json
  packages/ng-schematics/src/migrations/migration-collection.json
Labels: :white_check_mark: status: verified, migration, version: 14.3.x
