Repository IgniteUI/igniteui-cli, pull requests merged in 2025-02, with the labels that each got.

#1375 fix: add overrides for reveal sdk wrappers
  packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/_base/files/package.json
Labels: angular-modules, angular-standalone

#1376 chore: remove dv overrides
  packages/igx-templates/igx-ts-legacy/projects/_base/files/package.json
  packages/igx-templates/igx-ts/projects/_base/files/package.json
Labels: angular-modules, angular-standalone

#1377 chore: release version 14.3.13
  CHANGELOG.md
  packages/cli/package.json
  packages/core/package.json
  packages/igx-templates/package.json
  packages/ng-schematics/package.json
Labels: version: 14.3.x

#1381 chore(cli): release version 14.3.14
  CHANGELOG.md
  packages/cli/package.json
  packages/core/package.json
  packages/igx-templates/package.json
  packages/ng-schematics/package.json
Labels: version: 14.3.x

#1379 fix test errors
  packages/cli/package.json
  packages/cli/templates/react/igr-ts/projects/_base/files/vite.config.ts
  packages/cli/templates/webcomponents/igc-ts/projects/_base/files/eslint.config.mjs
  packages/cli/templates/webcomponents/igc-ts/projects/_base/files/src/app/app.test.ts
  packages/core/package.json
  packages/igx-templates/package.json
  packages/ng-schematics/package.json
Labels: angular-modules, :white_check_mark: status: verified, react, web-components, angular-standalone
